### ISSUE TITLE
SIGSEGV logging in BatchEnqueue

### ISSUE THREAD

**Issue by CorentinB** [internetarchive/Zeno#108]
![image](https://github.com/user-attachments/assets/1ce2d07d-287c-4e8b-ae56-a2bd8fdcb323)

(on `queue` branch)

**Comment by equals215** [comment]
related to https://github.com/internetarchive/Zeno/issues/92

**Comment by equals215** [comment]
On it

**Comment by equals215** [comment]
PR fixing it ready for review
