### ISSUE TITLE
Add PDF outlinks extraction

### ISSUE THREAD

**Issue by CorentinB** [internetarchive/Zeno#11]

**Comment by Qu-Ack** [comment]
I am trying to work on this issue and have successfully setup the codebase locally, just need a little help understanding the codebase and where would I add this feature?

**Comment by CorentinB** [comment]
> I am trying to work on this issue and have successfully setup the codebase locally, just need a little help understanding the codebase and where would I add this feature?

Hi! I'm so glad you want to contribute! Sadly right now we are in the middle of a big rewrite with many branches fixing many bugs not merged together yet, and the latest main commit has some bugs in it. We are working very hard to fix all of that in the next 2 weeks. If you are still interested in helping in 2 weeks, comment here again and we will see what we can do!

**Comment by Qu-Ack** [comment]
Thank you for responding, I will reach out to you in 2 weeks, if you need any help with the rewrite or want to pass on the boring stuff to someone else, I am open to help.

**Comment by CorentinB** [comment]
Hi @Qu-Ack did you have an idea for which lib you would use? I'm looking around and can't find a good one.
