### ISSUE TITLE
Define Zeno's queuing behavior properly

### ISSUE THREAD

**Issue by CorentinB** [internetarchive/Zeno#115]
As discussed with @equals215, Zeno's behavior in term of queuing should be as followed:

- By default: handover + WAL writes batching
- As an option: --disable-handover, --whatever (--whatever == a good argument name to ask for more atomicity == not use WAL batch writing)
- When using HQ: handover++ (no queuing AT ALL)

**Comment by equals215** [comment]
Options and defaults can be done in under a minute. Handover++ as you call it, can either be done on the fly or integrated to #113 in the channeling efforts, as you wish @CorentinB

**Comment by CorentinB** [comment]
I guess it should be integrated in #113.
