### ISSUE TITLE
More efficient deduplication hash table

### ISSUE THREAD

**Issue by NGTmeaty** [internetarchive/Zeno#14]
This is quite a half-baked idea, but we'd be looking to implement some sort of hit counter for items in the hash table, allowing us to clean it up when we've filled it up. This will also allow us to set a size "cap" on the table, helping during larger runs. 

- [ ] Hit counter and removal of items with low number of hits when we're running low on space
- [ ] File based storage of the hash table (somehow...)

**Comment by CorentinB** [comment]
@NGTmeaty why this got closed?

**Comment by NGTmeaty** [comment]
Out of scope from Zeno, more of a warc issue (and one that I don't think is particularly important right now)

**Comment by CorentinB** [comment]
> Out of scope from Zeno, more of a warc issue (and one that I don't think is particularly important right now)

Sorry didnt realize it was Zeno's repo.....
