### ISSUE TITLE
AWS and mismatch for User-Agent Zeno

### ISSUE THREAD

**Issue by tvb** [internetarchive/Zeno#43]
Hi @CorentinB,

See https://web.archive.org/web/20221119203341/https://www.coolblue.de/en/stores for context.

Is the `Internet Archive` organisation started to use this web crawler in the public? We started noticing requests from the Archive being blocked since the end of october by our AWS WAF BotControl rules because the user-agent is not matching [archive.org_bot](https://archive.org/details/archive.org_bot). 

If you check the request blocking details below you can see it missed the `label` name `awswaf:managed:aws:bot-control:bot:name:internet_archive` which would automatically be added if AWS recognized the request originating from the Internet Archive organisation. This mismatch is caused because the user-agent is not matching.

```
action BLOCK
formatVersion 1
httpRequest.clientIp 207.241.235.164
httpRequest.country US
httpRequest.headers.0.name Host
httpRequest.headers.0.value www.coolblue.de
httpRequest.headers.1.name User-Agent
httpRequest.headers.1.value Zeno
httpRequest.headers.2.name Accept-Encoding
httpRequest.headers.2.value gzip
httpRequest.headers.3.name Connection
httpRequest.headers.3.value close
httpRequest.httpMethod GET
httpRequest.httpVersion HTTP/1.1
httpRequest.requestId xxxxxxxxMELtQmGpKoibv3XfAfSMPkDRiNSZprf8ktWPMkrNg==
httpRequest.uri /en/stores
httpSourceId xxxxWA9W0E5
httpSourceName CF
labels.0.name awswaf:managed:token:absent
labels.1.name awswaf:managed:aws:bot-control:signal:non_browser_user_agent
...
ruleGroupList.5.ruleGroupId AWS#AWSManagedRulesBotControlRuleSet
ruleGroupList.5.terminatingRule.action BLOCK
ruleGroupList.5.terminatingRule.ruleId SignalNonBrowserUserAgent
terminatingRuleId AWSManagedRulesBotControlRuleSet
terminatingRuleType MANAGED_RULE_GROUP
timestamp 1668890021691
webaclId arn:aws:wafv2:us-east-1:xxxx:global/webacl/webshop-firewall-cf-webacl-v2/xxxxxx-41dc-9162-020f7bb917e3
```

**Comment by tvb** [comment]
@NGTmeaty May I assume this PR https://github.com/internetarchive/Zeno/pull/45 fixes this?

**Comment by NGTmeaty** [comment]
Yes, this should be resolved now. Thank you!
