### ISSUE TITLE
live-stats flag is broken

### ISSUE THREAD

**Issue by willmhowes** [internetarchive/Zeno#72]
Standard logging is interspersed with the expected `live-stats` information, which breaks with the previous behavior of the `live-stats` flag. In other words, as the typical logs fly by in the terminal window, Zeno is also repeatedly logging the live-stats info which then moves out of the viewport. The issue seems to be that Zeno is no longer suppressing the normal logging when the `--live-stats` flag is active. I've included a screenshot of the output of Zeno with the `--live-stats` flag below.

![Screenshot 2024-07-08 at 4 05 23 PM](https://github.com/internetarchive/Zeno/assets/39531537/94f85879-65d1-48d3-9d73-41238e53f74c)

**Comment by equals215** [comment]
made the fix fit in the to-be-merged PR at commit 8de40c4
