### ISSUE TITLE
Logs are written to the wrong location

### ISSUE THREAD

**Issue by willmhowes** [internetarchive/Zeno#73]
Logs are being written to the `/jobs` directory instead of the `/jobs/logs` directory

**Comment by nick2432** [comment]
can i work on this?

**Comment by equals215** [comment]
> can i work on this?

Sure, go ahead and fork the repo! Send a PR when you're done and assign me to it 😉

**Comment by nick2432** [comment]
@equals215  I've raised PR

**Comment by CorentinB** [comment]
Fixed by https://github.com/internetarchive/Zeno/commit/6ab2d19552eebeba8ea591a11e8df74a1027b70f
