### ISSUE TITLE
Replace github.com/clbanning/mxj/v2 with stdlib

### ISSUE THREAD

**Issue by CorentinB** [internetarchive/Zeno#84]
github.com/clbanning/mxj/v2 is being used for XML processing, I think it can be replaced by standard lib-only code.

**Comment by HarshNarayanJha** [comment]
I think I can do it

**Comment by CorentinB** [comment]
> I think I can do it

Thank you. Feel free to submit a PR.

**Comment by HarshNarayanJha** [comment]
But I can't seem to be able to run the project as that one dependency on `git.archive.org` is unreachable, but archive.org is functioning right now

**Comment by CorentinB** [comment]
> But I can't seem to be able to run the project as that one dependency on `git.archive.org` is unreachable, but archive.org is functioning right now
> 
> ```go
> 	git.archive.org/wb/gocrawlhq v1.2.13
> ```

This is now fixed
